version: '3.8' 
services:
  frontend:
    build:
      context: .
      target: build # This targets the build stage in your Dockerfile

  server:
    build: 
      context: .
      target: server # This targets the server stage in your Dockerfile
    ports:
      - "3000:3000" 
    depends_on:
      - frontend

  nginx:
    image: nginx:latest
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./server/public:/app/server/public:ro 
    depends_on:
      - server