FROM node:20.9.0
WORKDIR /app
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/PriyadasunKC/sms-host.git .
WORKDIR /app/server
RUN npm install
EXPOSE 5000
CMD ["npm", "start"]