# Client Dockerfile
FROM node:20.9.0 as build

WORKDIR /app

# Clone the repository
RUN apt-get update && apt-get install -y git
RUN git clone https://github.com/PriyadasunKC/sms-host.git .

# Navigate to the project directory
WORKDIR /app/project

# Install dependencies and build
RUN npm install
RUN npm run build

# Nginx stage
FROM nginx:alpine

# Install Nginx
RUN apk update && apk add nginx

# Copy the built files from the build stage
COPY --from=build /app/project/build /usr/share/nginx/html

# Copy Nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]